### ISSUE TITLE
example code failed: computeWeightedDeviations(SE, ukbb)

### ISSUE THREAD

**Issue by Winnie09** [caleblareau/gchromVAR#1]
Example codes from [gchromVAR User's Guide](https://caleblareau.github.io/gchromVAR/articles/gchromVAR_vignette.html) are implemented line by line and when it goes to the line:

> ukbb_wDEV <- computeWeightedDeviations(SE, ukbb)

There is an error:

> Error in nrow(counts_mat) == nrow(background_peaks) : 
>   the leading minor of order 2 is not positive definite

**Comment by caleblareau** [comment]
This would mean that the background peaks were not properly computed. 

Can you send me the output of 

head(rowRanges(SE))

and

summary(rowSums(assays(SE)[[“counts”]]))

**Comment by Winnie09** [comment]
Sure.

> head(rowRanges(SE))

GRanges object with 6 ranges and 1 metadata column:
      seqnames        ranges strand |              bias
         <Rle>     <IRanges>  <Rle> |         <numeric>
  [1]     chr1   10290-10790      * | 0.212121212121212
  [2]     chr1   13252-13752      * | 0.285714285714286
  [3]     chr1   16019-16519      * | 0.388888888888889
  [4]     chr1   29020-29520      * | 0.235294117647059
  [5]     chr1   96387-96887      * | 0.371428571428571
  [6]     chr1 115440-115940      * |           0.21875
  -------
  seqinfo: 23 sequences from an unspecified genome; no seqlengths
> summary(rowSums(assays(SE)[["counts"]]))

Min. 1st Qu. Median Mean 3rd Qu. Max.
17.0 185.0 266.0 771.6 545.0 67109.0

**Comment by caleblareau** [comment]
Hmm that all looks right. 

What about
length(rowRanges(SE))
dim(assays(SE)[[“counts”]]) 

?

**Comment by caleblareau** [comment]
Marking as closed given no additional comments
