### ISSUE TITLE
Do I need to normalize ATAC-seq matirx?

### ISSUE THREAD

**Issue by lzj1769** [caleblareau/gchromVAR#13]
Hi,

I am using gchromVAR to identify the cellular targets for disease by using snATAC-seq, and I have some fine-mapped SNPs.
I have clustered and annotated the cells and generated a bulk ATAC-seq matrix of peaks by cell types,
so do I need to do some normalization for this matrix before I use it as input?

Thanks!
Li

**Comment by julirsch** [comment]
Sounds like your good to go! The method will GC and library size normalize for you.

Jacob
