### ISSUE TITLE
count files and peak files

### ISSUE THREAD

**Issue by Renfang2019** [caleblareau/gchromVAR#2]
Dear Caleb,
Thank you for the gChromVAR, I am trying to use your gChromVAR for our bulk ATAC seq. I have narrowpeak files and bam files as well. 

 I have a basic questions about the files. for the files in gChromVAR, what is the count files, what is peak files?   Can I load two files at the same time into counts files and peak files? Thank you. I am new to this so please bear with me the simple questions. Thank you very much. 

Have a great day.

Renfang

**Comment by caleblareau** [comment]
Hi Renfang,

These inputs are definitely better described in the chromVAR documentation and paper, but as similar workflow has been described here: https://bioconductor.org/packages/release/bioc/vignettes/DiffBind/inst/doc/DiffBind.pdf <https://bioconductor.org/packages/release/bioc/vignettes/DiffBind/inst/doc/DiffBind.pdf>

In brief,

Peaks are a fixed width (e.g. 500 bp) file of genomic coordinates that describe the accessibility landscape of a set of samples. 

The counts file is a matrix of peaks x cells/samples where the entries are the number of fragments that overlap the region for the sample. This can be achieved by the chromVAR getPeaks function.

**Comment by Renfang2019** [comment]
Thank you so much Caleb! That makes big sense to make the files. I am learning the diffbind now. For the datasheet feeds into the diffbind, do I need to put all the real peaks into the sheet or just need the header? Thank you. Have a great day!Renfang

**Comment by caleblareau** [comment]
To clarify, I'm not advocating running diffbind _per se_ (and I haven't for running chromVAR or gchromVAR), but was simply mentioning that the analysis workflow to format inputs is best described in its documentation. 

I haven't run diffbind myself so I don't have means of answering this. Please consider asking this to the diffbind maintainers if you have questions running their tool.

**Comment by Renfang2019** [comment]
Thank you very much for help!

Dr. Renfang Song Taylor
Assistant Professor
Department of Biology
College of Science and Mathematics
SOUTHWEST BAPTIST UNIVERSITY
1600 University Ave. | Bolivar MO 65613
Room: Wheeler Science Center 114D
OFFICE 417.328.1669
rtaylor@SBUniv.edu Follow us: Facebook | Twitter | Instagram
Proverbs 2:10-11.For wisdom will enter your heart, and knowledge will be pleasant to your soul. and understanding will guard you.  箴言2：10-11智 慧 必 入 你 心 ． 你 的 靈 要 以 知 識 為 美 . 謀 略 必 護 衛 你 ． 聰 明 必 保 守 你

________________________________
