### ISSUE TITLE
input without weight

### ISSUE THREAD

**Issue by zji90** [caleblareau/gchromVAR#3]
hi,
Is it possible to just input the snp locations without the weights? The snp file is from public source and does not have weights with it.
Thanks!

**Comment by julirsch** [comment]
Hi @zji90,

You can, of course, give all SNPs of interest a weight of 1. Here, choosing which SNPs to include will likely change your results pretty drastically. In general, we would not suggest that you do this (although there is nothing stopping you in the implementation). For example, the approach you suggest is similar to the "chromVAR" (not g-chromVAR) approach in the paper (see Supplemental Figure 15-16) that showed decent sensitivity but a lack of specificity for identifying cell-type enrichments. 

Jacob

**Comment by zji90** [comment]
Thanks!
