### ISSUE TITLE
gchromVAR peaks

### ISSUE THREAD

**Issue by Renfang2019** [caleblareau/gchromVAR#4]
Dear Caleb,

This is Renfang again. I have been trying gchromVAR for a few days. when I try to get peaks, it showed me the errow that it could not determine start/end columns, any suggestions? thank you.

 peaksdf <- data.frame(peaksFile)
> peaks <- makeGRangesFromDataFrame(peaksdf, seqnames = "V1", start.field = "V2", end.field = "V3")
Error in .find_start_end_cols(df_colnames0, start.field0, end.field0) : 
  cannnot determine start/end columns

**Comment by caleblareau** [comment]
My guess is that peaksFile is a string that specifies the peak file?

You need to use read.table rather than data.frame to import the file; try:

peaksdf <- read.table(peaksFile)

**Comment by Renfang2019** [comment]
Thank you so much! I tried read table, import narrowpeaks,read.csv. It’s the same error. I tried different files as well. Is it possible I share one file and you try on your end?


Dr. Renfang Song Taylor
Assistant Professor
Department of Biology
College of Science and Mathematics
SOUTHWEST BAPTIST UNIVERSITY
1600 University Ave. | Bolivar MO 65613
Room: Wheeler Science Center 114D
OFFICE 417.328.1669
rtaylor@SBUniv.edu Follow us: Facebook | Twitter | Instagram
Proverbs 2:10-11.For wisdom will enter your heart, and knowledge will be pleasant to your soul. and understanding will guard you.  箴言2：10-11智 慧 必 入 你 心 ． 你 的 靈 要 以 知 識 為 美 . 謀 略 必 護 衛 你 ． 聰 明 必 保 守 你

________________________________

**Comment by Renfang2019** [comment]
Thank you so much. I tried again and it works on this step. I had an error that the col numbers are different. Any suggestions?
 nrows <- 131417
> ncols <- 10
> counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
countsFile <- counts
> peaksFile<- "E16WTc_nPN_peakschr.narrowPeak"
> peaksdf <- read.table(peaksFile)
> peaks <- makeGRangesFromDataFrame(peaksdf, seqnames = "V1", start.field = "V2", end.field = "V3")
> counts <-  data.matrix(countsFile)
> SE <- SummarizedExperiment(assays = list(counts = counts),
+                                rowData = peaks, 
+                                colData = DataFrame(names = colnames(counts)))
Error in validObject(.Object) : 
  invalid class “SummarizedExperiment” object: 
  nb of cols in 'assay' (10) must equal nb of rows in 'colData' (0)

**Comment by caleblareau** [comment]
Please see other thread.
