### ISSUE TITLE
SE part with colData errow

### ISSUE THREAD

**Issue by Renfang2019** [caleblareau/gchromVAR#5]
Thank you so much. I tried again and it works on this step. I had an error that the col numbers are different. Any suggestions? I make the colData <- DataFrame. The DataFrame is the excel sheet with the sample name E16WTc_nPN_peakchr.narrowPeak, and sample type E16, saved as csv.

**colData = DataFrame(names = colnames(counts))** what this part should look like?

nrows <- 131417

ncols <- 10
counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
countsFile <- counts
peaksFile<- "E16WTc_nPN_peakschr.narrowPeak"
peaksdf <- read.table(peaksFile)
peaks <- makeGRangesFromDataFrame(peaksdf, seqnames = "V1", start.field = "V2", end.field = "V3")
counts <- data.matrix(countsFile)
SE <- SummarizedExperiment(assays = list(counts = counts),

                           rowData = peaks, 
                           colData = DataFrame(names = colnames(counts)))
Error in validObject(.Object) :
invalid class “SummarizedExperiment” object:
nb of cols in 'assay' (10) must equal nb of rows in 'colData' (0)

**Comment by caleblareau** [comment]
Maybe after the line 
`countsFile <- counts`
add
```
colnames(countsFile) <- paste0("sample", as.character(1:dim(countsFile)[2])
```

The error that you are running into is that there aren't column names associated with your simulated counts matrix, but there typically would be with real data.
