### ISSUE TITLE
gchromVAR installation

### ISSUE THREAD

**Issue by Renfang2019** [caleblareau/gchromVAR#6]
Dear Caleb,Thank you very much for the help. I add the line for colname and it worked! so I am in the step of importbedscore. It said there is no function of importbedscore so I tried to install the package again and it gave me this error. Any other way to install it? Thank you !

> devtools::install_github("caleblareau/gchromVAR")
Downloading GitHub repo caleblareau/gchromVAR@master
Skipping 1 packages not available: chromVARmotifs
Installing 3 packages: chromVARmotifs, motifmatchr, RSQLite
Installing packages into ‘C:/Users/rsong/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: Failed to install 'gchromVAR' from GitHub:
  (converted from warning) package ‘chromVARmotifs’ is not available (for R version 3.5.1)

**Comment by Renfang2019** [comment]
I tried different computer and it installed gchromVAR nicely! Thank you.

**Comment by julirsch** [comment]
Hi @Renfang2019,

Out of curiosity, did you switch to OSX or Linux?

Jacob

**Comment by Renfang2019** [comment]
Yes, I used the Windows yesterday and I tried on apple today.


Dr. Renfang Song Taylor
Assistant Professor
Department of Biology
College of Science and Mathematics
SOUTHWEST BAPTIST UNIVERSITY
1600 University Ave. | Bolivar MO 65613
Room: Wheeler Science Center 114D
OFFICE 417.328.1669
rtaylor@SBUniv.edu<mailto:cmarsch@SBUniv.edu> Follow us: Facebook<https://www.facebook.com/SBUniv> | Twitter<http://www.twitter.com/SBUniv> | Instagram[cid:0379be4a-e2eb-4685-943c-ba439fe5223c]<http://www.instagram.com/sbuniv>

Proverbs 2:10-11.For wisdom will enter your heart, and knowledge will be pleasant to your soul. and understanding will guard you.  箴言2：10-11智 慧 必 入 你 心 ． 你 的 靈 要 以 知 識 為 美 . 謀 略 必 護 衛 你 ． 聰 明 必 保 守 你

________________________________
