### ISSUE TITLE
importBedScore function

### ISSUE THREAD

**Issue by Renfang2019** [caleblareau/gchromVAR#7]
Dear Caleb,
I installed gchromVAR and run the importBedScore, it gives me an error like this , any suggestions? Thank you so much!

nrows <- 131417
> ncols <- 10
> counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
> countsFile <- counts
> colnames(countsFile) <- paste0("E16WTc_nPN_peakschr.narrowPeak", as.character(1:dim(countsFile)[2]))
> peaksFile<- "E16WTc_nPN_peakschr.narrowPeak"
> peaksdf <- read.table(peaksFile)
> peaks <- makeGRangesFromDataFrame(peaksdf, seqnames = "V1", start.field = "V2", end.field = "V3")
> counts <-  data.matrix(countsFile)
> SE <- SummarizedExperiment(assays = list(counts = counts),
+                                rowData = peaks, 
+                                colData = DataFrame(names = colnames(counts)))
> SE <- addGCBias(SE, genome = BSgenome.Mmusculus.UCSC.mm10)
> E16 <- importBedScore(rowRanges(SE), peaks1, colidx = 5)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘importBedScore’ for signature ‘"GRanges", "GRanges"’

**Comment by julirsch** [comment]
It looks like chromVAR functions `addGCBias` are loaded and working but not gchromVAR functions `importBedScore`. Is the gchromVAR package loaded i.e. `library(gchromvar)`?

**Comment by Renfang2019** [comment]
yes, I loaded both chromVAR and gchromVAR

**Comment by Renfang2019** [comment]
@julirsch Thank you for reply. I have been trying chromVAR and gchromVAR but did not get any luck to push through the first step to get the counts on chromVAR. I am getting crazy :) Anyhelp will be appreciated!

**Comment by inabro** [comment]
Did you manage to solve this problem? I am facing the exact same error
